### 异常处理

>  用运行时异常表示编程错误，如果在该方法出就捕获然后处理就用try Catch。

>  如下代码块表示直接在方法test1()中捕获了代码，然后处理了，代码继续往下走吧。

```
public static void test1() {
try {
    int i = 12 / 0;
    System.out.println(i);
} catch (Exception e) {
    e.printStackTrace();
}
}
```

> 捕获之后处理了还可以继续往上面重新抛出去
```
public static void test4() {
try {
    int i = 12 / 0;
    System.out.println(i);
} catch (Exception e) {
    e.printStackTrace();
    throw new ArithmeticException();
}
}
```

> 或者可以不处理直接往上面抛异常 用关键字 throw

```
public static void test2() {
int a = 12, b = 0, c;
if (b == 0)
    throw new ArithmeticException();
c = a / b;
}
```

> 或者直接在方法上抛出用关键字 throws

```
public static void test3() throws ArithmeticException{
int a = 12, b = 0, c;
c = a / b;
}
```
